version: 2
jobs:
  python_build_and_test:
    docker:
      - image: circleci/python:3.6
        environment:
          AWS_ACCESS_KEY_ID: placeholder
          AWS_SECRET_ACCESS_KEY: placeholder
          AWS_DEFAULT_REGION: us-east-1
      - image: cnadiminti/dynamodb-local
    steps:
      - checkout
      - run: sudo apt install python3-virtualenv
      - run: make mock
      - run: make pytest

  node_build_and_test:
    docker:
      - image: circleci/node:8
        environment:
          AWS_ACCESS_KEY_ID: placeholder
          AWS_SECRET_ACCESS_KEY: placeholder
          AWS_DEFAULT_REGION: us-east-1
      - image: redis
    steps:
      - checkout
      - run: npm install
      - run: make mock
      - run: make nodesetup
      - run: make jstest

  golang_build_and_test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8
        environment:
          AWS_ACCESS_KEY_ID: placeholder
          AWS_SECRET_ACCESS_KEY: placeholder
          AWS_DEFAULT_REGION: us-east-1
      - image: postgres
        environment:
          POSTGRES_PASSWORD: secret
      - image: redis
      - image: cnadiminti/dynamodb-local
    steps:
      - checkout
      - run: make mock
      - run: make bin
      - run: make gotest
workflows:
  version: 2
  build_and_test:
    jobs:
      - python_build_and_test
      - node_build_and_test
      - golang_build_and_test
